### ISSUE TITLE
broken links, bad markdown rendering

### ISSUE THREAD

**Issue by sdrobertw** [96boards/projects#14]
@Mani-Sadhasivam , please review your work.

There is a broken link I found and mentioned a while back in part-3 of your home surveillance project

https://github.com/96boards/projects/tree/master/home_surveillance/part-3

Please fix this and ensure there is nothing else throughout all remaining parts.

**Comment by Mani-Sadhasivam** [comment]
Fixed in following commits: 
https://github.com/96boards/projects/commit/b449309131484619e36fdc1badf89b583efc6ffb 
https://github.com/96boards/projects/commit/103c630c3728cb62fe164672f1c3b7e1e7c130d7
