### ISSUE TITLE
Consistency throughout all projects

### ISSUE THREAD

**Issue by sdrobertw** [96boards/projects#17]
@Mani-Sadhasivam could you or @radhikap18 please bring all projects up to par.

Original projects are not consistant with the new format we decided on. The template/contribution seems to need updating as well.

Thanks!

**Comment by radhikap18** [comment]
I'll do that

**Comment by Mani-Sadhasivam** [comment]
@radhikap18 Thanks for doing!
@sdrobertw  Thanks for pointing out!

**Comment by sdrobertw** [comment]
It looks like this was taken care of, Thanks @radhikap18
