### ISSUE TITLE
Adding comments and README.md to new projects

### ISSUE THREAD

**Issue by sdrobertw** [96boards/projects#6]
@radhikap18 

Please make sure to add comments to your code for both magic8[1] and hourglass[2] projects. 

You will also need to add README.md files with description of your project and instructions for recreation. Please follow the instructions and guidelines in the CONTRIBUTION.md[3]

[1] https://github.com/96boards/projects/tree/master/magic8
[2] https://github.com/96boards/projects/tree/master/hourglass
[3] https://github.com/96boards/projects/blob/master/CONTRIBUTE.md

**Comment by Mani-Sadhasivam** [comment]
Couple of things to add:

1. Don't add any binaries to repo unless it is mandatory
2. Submitted project should be in good shape (i.e it should build and execute)
3. Nice to have a crisp title for PR and a description

**Comment by sdrobertw** [comment]
It looks like this was taken care of. Please make sure all future code is commented.
